name: tezda
description: Creating a truly unique shopping experience for customers
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get_it: ^7.6.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  dio: ^5.1.2
  dio_cache_interceptor: ^3.5.0
  dots_indicator: ^3.0.0
  encrypt: ^5.0.1
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_messaging: ^14.6.2
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^14.1.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.3.0
  mockito: ^5.4.0
  network_info_plus: ^4.0.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  pattern_formatter: ^3.0.0
  pretty_dio_logger: ^1.3.1
  share_plus: ^7.0.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.4
  store_redirect: ^2.0.1
  supercharged: ^2.1.1
  unique_identifier: ^0.3.0
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - env/dev.env
    - env/staging.env
    - env/prod.env
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/gifs/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-Black.ttf
